/// Flutter icons IconPlane
/// Copyright (C) 2024 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  IconPlane
///      fonts:
///       - asset: fonts/IconPlane.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class IconPlane {
  IconPlane._();

  static const _kFontFam = 'IconPlane';
  static const String? _kFontPkg = null;

  static const IconData ic_plane = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
