/// Flutter icons IconLocation
/// Copyright (C) 2024 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  IconLocation
///      fonts:
///       - asset: fonts/IconLocation.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class IconLocation {
  IconLocation._();

  static const _kFontFam = 'IconLocation';
  static const String? _kFontPkg = null;

  static const IconData ic_location = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
